# Generated by Django 5.2.3 on 2025-06-12 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên danh mục')),
                ('slug', models.SlugField(help_text='Phần thân thiện với URL, tự động tạo từ tên nếu để trống.', max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Các danh mục',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên sản phẩm')),
                ('description', models.TextField(verbose_name='Mô tả sản phẩm')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá')),
                ('image', models.ImageField(upload_to='cameras/', verbose_name='Hình ảnh sản phẩm')),
                ('resolution', models.CharField(blank=True, max_length=100, verbose_name='Độ phân giải')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='Là sản phẩm bán chạy?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cameras', to='products.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Các Camera',
                'ordering': ['-created_at'],
            },
        ),
    ]
