# Generated by Django 5.2.3 on 2025-06-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Giá gốc (nếu có)'),
        ),
        migrations.AddField(
            model_name='camera',
            name='spec_line_1',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dòng thông số 1'),
        ),
        migrations.AddField(
            model_name='camera',
            name='spec_line_2',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dòng thông số 2'),
        ),
        migrations.AddField(
            model_name='camera',
            name='spec_line_3',
            field=models.CharField(blank=True, max_length=255, verbose_name='Dòng thông số 3'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá bán'),
        ),
    ]
