# Generated by Django 5.2.3 on 2025-06-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_camera_original_price_camera_spec_line_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='Icon danh mục'),
        ),
    ]
